name: pages build and deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build dist
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-pages-artifact@v1

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1
